// Virtual modules generated by the `lucideIconBuckets` plugin in vite.config.ts.
// Used only by src/lib/utils/lucide-icon.ts.

declare module 'virtual:lucide-icons/aliases' {
	const aliases: Record<string, string>;
	export default aliases;
}

declare module 'virtual:lucide-icons/*' {
	const icons: Record<string, import('svelte').Component>;
	export default icons;
}
